export const trendingData = {
  title: "GitHub 昨日热榜",
  dateText: "2026-06-02",
  accentColor: "#F78166",
  repos: [
    {
      rank: 1,
      owner: "microsoft",
      repo: "markitdown",
      description: "把 Office 文档转成干净的 Markdown,丢给 LLM 之前必装。",
      starsToday: 3618,
      totalStars: 51200,
      language: "Python",
      languageColor: "#3572A5",
      features: "支持 PDF、Word、Excel、PowerPoint 等几十种格式,一键转成干净的 Markdown,微软官方出品。",
      useCase: "RAG 工程师的必备工具——喂给大模型之前先用它预处理,token 消耗直降 70% 以上,准确率反而更高。",
      techHighlight: "底层用 python-markdown 和 pandoc,纯 Python 实现,提供 MCP server 接口,可直接挂进 Claude Desktop。",
      url: "github.com/microsoft/markitdown",
    },
    {
      rank: 2,
      owner: "nesquena",
      repo: "hermes-webui",
      description: "Hermes Agent 的 Web/手机控制台,远程管理你的 AI Agent 任务。",
      starsToday: 1722,
      totalStars: 8400,
      language: "Python",
      languageColor: "#3572A5",
      features: "Hermes Agent 的 Web 界面,让 AI Agent 不只在终端跑,也能在浏览器和手机上远程操控。",
      useCase: "7×24 跑长任务的用户必备——长视频渲染、数据爬虫、CI 监控,从手机就能查看进度、调整参数。",
      techHighlight: "后端 FastAPI + WebSocket 实时推送,前端 React 18 + Vite,一条命令部署,延迟控制在 100ms 以内。",
      url: "github.com/nesquena/hermes-webui",
    },
    {
      rank: 3,
      owner: "affaan-m",
      repo: "ECC",
      description: "Agent harness 性能优化系统:Skills、Instincts、Memory、Security 全部就位。",
      starsToday: 1533,
      totalStars: 6100,
      language: "JavaScript",
      languageColor: "#F1E05A",
      features: "Agent harness 性能优化系统,提供 Skills、Instincts、Memory、Security 四个核心模块。",
      useCase: "Claude Code、Codex、Cursor 用户装上后,Agent 自动学会什么时候用工具、怎么用,错误调用减少 30%。",
      techHighlight: "首创 Instincts 机制——给 Agent 装上条件反射,基于上下文自动注入最佳实践,无需写 prompt 也能跑稳。",
      url: "github.com/affaan-m/ECC",
    },
    {
      rank: 4,
      owner: "chopratejas",
      repo: "headroom",
      description: "压缩 LLM 输入的工具输出/日志/RAG chunk,省 60-95% token,答案不变。",
      starsToday: 1265,
      totalStars: 3700,
      language: "Python",
      languageColor: "#3572A5",
      features: "LLM 上下文压缩器,在 token 进模型之前自动瘦身 60% 到 95%,答案质量不变。",
      useCase: "RAG 检索结果太多塞不下 context window?Headroom 帮你智能去重和截断,token 成本直接砍半。",
      techHighlight: "提供三种部署形态:Python 库、HTTP 代理、MCP server。无侵入接入任何 LLM 工作流,5 分钟上线。",
      url: "github.com/chopratejas/headroom",
    },
    {
      rank: 5,
      owner: "OpenBMB",
      repo: "VoxCPM",
      description: "Tokenizer-Free TTS 多语言语音生成 + 创意声音设计 + 真实人声克隆。",
      starsToday: 783,
      totalStars: 4200,
      language: "Python",
      languageColor: "#3572A5",
      features: "无 tokenizer 的 TTS 引擎,多语言语音生成、创意声音设计、真实人声克隆三合一。",
      useCase: "播客、有声书、视频配音,给一段文本就出 24kHz 高质量音频,支持中英日韩粤语五种语言。",
      techHighlight: "基于 AR 语言模型 + flow matching,首次实现 tokenizer-free 端到端 TTS,推理速度比 VALL-E 快 3 倍。",
      url: "github.com/OpenBMB/VoxCPM",
    },
  ],
};
